### PR TITLE
Do not allow easy setting of username to something else

### PR DESCRIPTION
**Pull request by yuvipanda**

### CODE REVIEW

**Comment by jayvdb** [comment]
+1

**Comment by legoktm** [comment]
Erm...you need to set `usernames` if you're working on a non-Wikipedia right?

**Comment by yuvipanda** [comment]
@legoktm fixed in https://github.com/yuvipanda/paws/commit/644a8ed77cf20fc2d02ecdc81e7519402beddbbb

**Comment by legoktm** [comment]
But how does that work if you're working across multiple families now? Like importing data from mediawiki.org to Wikidata...?

**Comment by yuvipanda** [comment]
@legoktm I suppose that requires fixing the ['*'] bug for families?

**Comment by yuvipanda** [comment]
I reverted this since it deleted the usernames variable from globals(), thus making everything fail...

**Pull request merged**
