### PR TITLE
Install dev-requirements for pwb

### PR DESCRIPTION
**Pull request by yuvipanda**

### CODE REVIEW

**Comment by jayvdb** [comment]
why not use dev-requirements.txt maintained by pywikibot team for each branch ?

**Comment by yuvipanda** [comment]
Mostly because it has conditionals which will require that I use a newer pip. 

The reason I'm not using it for requirements.txt is because it installs Pillow, which brings in a *lot* of dependencies.

**Comment by jayvdb** [comment]
using newer pip is sane. and..umm:

```
$ sed -ie '/Pillow/d' requirements.txt
```

**Comment by yuvipanda** [comment]
Using `sed` in Dockerfiles is a bad code smell, easily spirals down to https://github.com/eugeneware/docker-wordpress-nginx/blob/master/Dockerfile

**Comment by yuvipanda** [comment]
I can probably fix that with a 'install pwb' bash script in a separate commit, actually.

**Comment by yuvipanda** [comment]
Also doing sed makes the git checkout dirty.

**Comment by jayvdb** [comment]
dirty checkout is a valid point, but easily avoided as you can (and should) put the modified requirements.txt out of the source tree before using it.

You are manually doing the equivalent of that sed in your Dockerfile- IMO it is clearer and more resilient to remove one line than specify your own list of dependencies, which are not maintained when the branches dependencies are changed.

**Comment by yuvipanda** [comment]
Yup, you're right. I'm modifying this, stand by.

**Comment by yuvipanda** [comment]
https://github.com/yuvipanda/paws/pull/10

**Pull request closed without merging**
